### ISSUE TITLE
Can't add expense

### ISSUE THREAD

**Issue by rafaces** [leMaik/moneylover-cli#6]
It's not possible to add an expense;
`Could not add expense { Error: Error 1, sync_error_data_invalid_format
    at MoneyLoverClient._postRequest (/node_modules/moneylover-cli/src/moneylover.js:21:21)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7) code: 1, originalMessage: 'sync_error_data_invalid_format' }`

I'm trying to debug and figure out which field is in the incorrect format, but haven't been able to do so;
Any clues?

**Comment by rafaces** [comment]
Opened a PR fixing the issue: https://github.com/leMaik/moneylover-cli/pull/7

**Comment by leMaik** [comment]
@rafaces Thanks for the bug report and the fix! :+1: I released v0.5.1 that includes it.
